#!/bin/bash
#purpose:find biggest number among four to satissfy if else if condition
echo "Read a b c d values"
read a
read b
read c
read d

if [ $a -gt $b -a $a -gt $c -a $a -gt $d ]
then
echo "$a a is big"
elif [ $b -gt $c -a $b -gt $d ]
then
echo "$b b is big"
elif [ $c -gt $d ]
then
echo "$c c is big"
else
echo "$d is big"
fi
